# -*- coding: utf-8 -*-
"""Panda Practice_Simon.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t3wfFN3Gys25w9Qm_A6_gs9o8bV84HjH
"""

#1. Basic Flitering

import pandas as pd

data = {'Name': ['Alice', 'Bob', 'Charlie'],
           'Age': [25, 30, 35],
           'Salary': [50000, 60000, 70000]}

df = pd.DataFrame(data)

#Command to filter rows for "Age" greater than 28

filtered_data = df[df['Age']>28]

print(filtered_data)

#2. Multiple Conditions

filtered_data = df[(df['Age']>28) & (df['Salary']<70000)]

print(filtered_data)

#3. String Matching

data = {'Name': ['Alice', 'Bob', 'Charlie','Simon'],
         'City':['Bangkok','Sydney','Queens','NewYork']}

df = pd.DataFrame(data)

filtered_data = df[df['City'].str.startswith('S')]

print(filtered_data)

#4. isin() Function

data['Department']= ['HR', 'IT', 'Finance', 'HR']
df = pd.DataFrame(data)

filtered_data = df[df['Department'].isin(['HR', 'Finance'])]

print(filtered_data)

#5. Filtering with Query
data['Grade']= ['A', 'B', 'C', 'A']

df = pd.DataFrame(data)

data['Marks']= [90, 80, 75, 95]

df = pd.DataFrame(data)

# Query to filter rows
filtered_data = df[(df['Grade'] == 'A') & (df['Marks'] > 85)]

#6. Null Values

data['Experience']= [2, 6, None, 4]

df = pd.DataFrame(data)

filtered_data = df.dropna()

print(filtered_data)

#7. Contains Method

data['Email']= ['test1@example.com', 'test2@gmail.com', 'admin@yahoo.com', 'simon@gmail.com']
df = pd.DataFrame(data)

filtered_data = df[df['Email'].str.contains('@gmail.com')]

print(filtered_data)

#8. Filter by Index

df= pd.DataFrame(data, index=['a', 'b', 'c', 'd'])

filtered_data = df.loc[['a', 'c']]

print(filtered_data)

#9. Using Lambda Functions

data['Age']= [23, 32, 46, 20]
df = pd.DataFrame(data)

filtered_data = df[df['Age'].apply(lambda x: x % 2 == 0)]

print(filtered_data)

#10.

data['Salary']= [55500, 95000, 80000, 62000]
df = pd.DataFrame(data)

filtered_data = df[df['Salary'].between(55000, 65000)]

print(filtered_data)